### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'List<Widget>

### ISSUE THREAD

**Issue by kangsudal** [kangsudal/kkungflix#4]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building StreamBuilder<QuerySnapshot>(dirty, state:
_StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>>#a9bf8):
type 'List<dynamic>' is not a subtype of type 'List<Widget>'

The relevant error-causing widget was:
  StreamBuilder<QuerySnapshot>
  file:///D:/AndroidStudioProjects/netflix_clone/lib/screen/search_screen.dart:117:12

When the exception was thrown, this was the stack:
#0      _SearchScreenState._buildList (package:netflix_clone/screen/search_screen.dart:142:14)
#1      _SearchScreenState._buildBody.<anonymous closure> (package:netflix_clone/screen/search_screen.dart:123:16)
#2      StreamBuilder.build (package:flutter/src/widgets/async.dart:545:81)
#3      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:124:48)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#8      StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#10     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5503:32)
#11     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6105:17)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#15     StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#19     ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#25     StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#30     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2694:33)
#31     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:873:21)
#32     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#33     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#34     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#35     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#39     _invoke (dart:ui/hooks.dart:161:10)
#40     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
#41     _drawFrame (dart:ui/hooks.dart:120:31)
(elided 3 frames from dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: A RenderFlex overflowed by 99473 pixels on the bottom.

Another exception was thrown: type 'List<dynamic>' is not a subtype of type 'List<Widget>'

**Comment by kangsudal** [comment]
```dynamic _buildListItem(BuildContext context, DocumentSnapshot data)```
를

```Widget _buildListItem(BuildContext context, DocumentSnapshot data)```
로 바꿔주면 된다.
