### ISSUE TITLE
에뮬레이터 변경후 이미지 안나옴

### ISSUE THREAD

**Issue by kangsudal** [kangsudal/kkungflix#8]
![에뮬레이터 변경후 이미지안나옴](https://user-images.githubusercontent.com/32862869/115228707-1150e500-a14d-11eb-9443-8f5198d8a33a.PNG)

#7 Pixel 3a 에뮬레이터로 실행

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 6.0 pixels on the bottom.

The relevant error-causing widget was: 
  Tab file:///D:/AndroidStudioProjects/netflix_clone/lib/widget/bottom_bar.dart:32:13
: To inspect this widget in Flutter DevTools, visit: http://127.0.0.1:9102/#/inspector?uri=http%3A%2F%2F127.0.0.1%3A50251%2FbzKcorobZX8%3D%2F&inspectorRef=inspector-0
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#51430 relayoutBoundary=up11 OVERFLOWING
...  parentData: offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(0.0<=w<=66.2, 0.0<=h<=48.0)
...  size: Size(66.0, 48.0)
...  direction: vertical
...  mainAxisAlignment: center
...  mainAxisSize: max
...  crossAxisAlignment: center
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════
W/DynamiteModule( 9921): Local module descriptor class for providerinstaller not found.
I/DynamiteModule( 9921): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 9921): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
W/sudal.kkungfli( 9921): Unknown chunk type '200'.
I/sudal.kkungfli( 9921): The ClassLoaderContext is a special shared library.
I/chatty  ( 9921): uid=10086(com.kangsudal.kkungflix) AsyncTask #2 identical 1 line
I/sudal.kkungfli( 9921): The ClassLoaderContext is a special shared library.
W/sudal.kkungfli( 9921): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
V/NativeCrypto( 9921): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 287 native methods...
W/sudal.kkungfli( 9921): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light greylist, reflection)
I/ProviderInstaller( 9921): Installed default security provider GmsCore_OpenSSL
W/sudal.kkungfli( 9921): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
W/sudal.kkungfli( 9921): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
W/sudal.kkungfli( 9921): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
W/sudal.kkungfli( 9921): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
W/sudal.kkungfli( 9921): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light greylist, reflection)

════════ Exception caught by image resource service ════════════════════════════════════════════════
The following StateError was thrown resolving an image codec:
Bad state: Insecure HTTP is not allowed by platform: http://t1.daumcdn.net/movie/cd87eb52410d9c20b0fd2b57c933b092e1547147

When the exception was thrown, this was the stack: 
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2434:7)
#1      _HttpClient.getUrl (dart:_http/http_impl.dart:2346:48)
#2      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:89:59)
#3      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:50:14)
#4      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:503:13)
...
Image provider: NetworkImage("http://t1.daumcdn.net/movie/cd87eb52410d9c20b0fd2b57c933b092e1547147", scale: 1.0)
Image key: NetworkImage("http://t1.daumcdn.net/movie/cd87eb52410d9c20b0fd2b57c933b092e1547147", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
W/sudal.kkungfli( 9921): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (light greylist, linking)
W/sudal.kkungfli( 9921): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)

════════ Exception caught by image resource service ════════════════════════════════════════════════
Bad state: Insecure HTTP is not allowed by platform: http://t1.daumcdn.net/cfile/1222D010A787894D94
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by kangsudal** [comment]
bottom_bar.dart:32:13 저장한콘텐츠목록 글씨 사이즈를 줄여주었다.

Bad state: Insecure HTTP is not allowed by platform
https://reasley.com/?p=4139

**Comment by kangsudal** [comment]
════════ Exception caught by image resource service ════════════════════════════════════════════════
The following StateError was thrown resolving an image codec:
Bad state: Insecure HTTP is not allowed by platform: http://t1.daumcdn.net/movie/cd87eb52410d9c20b0fd2b57c933b092e1547147

When the exception was thrown, this was the stack: 
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2434:7)
#1      _HttpClient.getUrl (dart:_http/http_impl.dart:2346:48)
#2      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:89:59)
#3      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:50:14)
#4      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:503:13)
...
Image provider: NetworkImage("http://t1.daumcdn.net/movie/cd87eb52410d9c20b0fd2b57c933b092e1547147", scale: 1.0)
Image key: NetworkImage("http://t1.daumcdn.net/movie/cd87eb52410d9c20b0fd2b57c933b092e1547147", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════════════════════════
Bad state: Insecure HTTP is not allowed by platform: http://t1.daumcdn.net/cfile/1222D010A787894D94
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by kangsudal** [comment]
firestore의 이미지 url을 https로 바꾸어주어 해결
