### ISSUE TITLE
type 'MappedListIterable<QueryDocumentSnapshot, dynamic>' is not a subtype of type 'List<Widget>'

### ISSUE THREAD

**Issue by kangsudal** [kangsudal/kkungflix#9]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following _TypeError was thrown building StreamBuilder<QuerySnapshot>(dirty, state: _StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>>#26f66):
type 'MappedListIterable<QueryDocumentSnapshot, dynamic>' is not a subtype of type 'List<Widget>'

The relevant error-causing widget was: 
  StreamBuilder<QuerySnapshot> file:///D:/AndroidStudioProjects/netflix_clone/lib/screen/like_screen.dart:12:12
When the exception was thrown, this was the stack: 
#0      _LikeScreenState._buildList (package:netflix_clone/screen/like_screen.dart:60:24)
#1      _LikeScreenState._buildBody.<anonymous closure> (package:netflix_clone/screen/like_screen.dart:15:16)
#2      StreamBuilder.build (package:flutter/src/widgets/async.dart:545:81)
#3      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:124:48)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
A RenderFlex overflowed by 99350 pixels on the bottom.
The relevant error-causing widget was: 
  Column file:///D:/AndroidStudioProjects/netflix_clone/lib/screen/like_screen.dart:26:14
════════════════════════════════════════════════════════════════════════════════════════════════════

![is not a subtype of type](https://user-images.githubusercontent.com/32862869/115658032-ef38ac00-a372-11eb-8d2f-54e6467d055e.PNG)

**Comment by kangsudal** [comment]
https://stackoverflow.com/questions/57486419/mappedlistiterable-is-not-a-subtype


```
Widget _buildList(BuildContext context, List<DocumentSnapshot> docs) {
    return Expanded(
      child: GridView.count(
        crossAxisCount: 3,
        childAspectRatio: 1 / 1.5,
        padding: EdgeInsets.all(3),
        children: (docs.map(
          (data) => _buildListItem(context, data),
        )).toList(),
      ),
    );
  }
```
  children: (docs.map(
          (data) => _buildListItem(context, data),
        )).**toList()**,

**Widget** _buildListItem
